"""Provider for the conversation-simple-v1 harness.

LLM-first: when ``HarnessLLMClient`` is configured, replies are generated by
the LLM (multi-turn, context-aware). Otherwise falls back to the rule-based
:class:`rule_based_fallback` and records ``llm_not_configured`` warning.
"""

from __future__ import annotations

from src.apps.api.app.agents.conversation_harness.contracts import (
    ConversationHarnessRequest,
    ConversationHarnessResult,
)
from src.apps.api.app.agents.conversation_harness.versions.simple_v1.runtime import (
    RUNTIME_VERSION,
    run_with_llm_fallback,
)


class ConversationSimpleV1Provider:
    version = "conversation-simple-v1"

    def run(self, request: ConversationHarnessRequest) -> ConversationHarnessResult:
        answer, traces, warnings, tool_calls, raw = run_with_llm_fallback(request)

        result = ConversationHarnessResult(
            conversation_harness_version=self.version,
            runtime_version=RUNTIME_VERSION,
            assistant_message=answer["assistant_message"],
            intent=answer.get("intent", {"type": "llm"} if raw.get("llm_used") else {"type": "unknown"}),
            citations=list(answer.get("citations", [])),
            tool_calls=tool_calls,
            action_proposals=list(answer.get("action_proposals", [])),
            effects=[],
            traces=traces,
            warnings=warnings,
            raw=raw,
        )
        result.to_dict()
        return result
